//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City_Info()
        {
            this.Emp_Info = new HashSet<Emp_Info>();
        }
    
        public int City_Id { get; set; }
        public Nullable<int> State_RefId { get; set; }
        public string City_Name { get; set; }
    
        public virtual State_info State_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Info> Emp_Info { get; set; }
    }
}
