//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Info
    {
        public int Id { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Address { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> City { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Phone { get; set; }
    
        public virtual City_Info City_Info { get; set; }
        public virtual Country_Info Country_Info { get; set; }
        public virtual State_info State_info { get; set; }
    }
}
